name: videowill

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  video_player: 0.10.11+1
  flutter_ffmpeg: 0.2.10
  google_speech: 1.0.2
  file_picker: 1.12.0
  path_provider: 1.6.11
  firebase_core: 0.4.0+8
  firebase_storage: 3.0.4
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

